import type { CaptionStyle } from './captions';

const noBox = { type: 'none', color: 'transparent', radius: 0, padX: 0, padY: 0 } as const;
const softShadow = { color: 'rgba(0,0,0,0.55)', blur: 12, x: 0, y: 4 };

export const STYLES: CaptionStyle[] = [
  // ---------- Glass ----------
  {
    id: 'liquid-glass',
    label: 'Liquid Glass',
    category: 'glass',
    font: { family: 'Gilroy', weight: 600, size: 66, uppercase: false, letterSpacing: 0 },
    color: '#FFFFFF',
    highlightColor: '#FFFFFF',
    highlightMode: 'dim',
    shadow: { color: 'rgba(0,0,0,0.25)', blur: 8, x: 0, y: 2 },
    container: { type: 'glass', tint: 'light', color: 'rgba(255,255,255,0.16)', radius: 44, padX: 44, padY: 26, blur: 28, border: 'rgba(255,255,255,0.45)' },
    display: 'phrase',
    animation: { type: 'blurIn', scope: 'phrase', duration: 0.35 },
    y: 0.72,
    maxWidth: 0.84,
  },
  {
    id: 'dark-glass',
    label: 'Dark Glass',
    category: 'glass',
    font: { family: 'Poppins', weight: 700, size: 62, uppercase: false, letterSpacing: 0 },
    color: '#FFFFFF',
    highlightColor: '#FFD60A',
    highlightMode: 'color',
    container: { type: 'glass', tint: 'dark', color: 'rgba(20,20,28,0.38)', radius: 40, padX: 40, padY: 24, blur: 30, border: 'rgba(255,255,255,0.18)' },
    display: 'phrase',
    animation: { type: 'slideUp', scope: 'word', duration: 0.35, stagger: 0.05 },
    y: 0.72,
    maxWidth: 0.84,
  },
  {
    id: 'glass-pop',
    label: 'Glass Pop',
    category: 'glass',
    font: { family: 'Montserrat', weight: 800, size: 66, uppercase: true, letterSpacing: 0 },
    color: '#FFFFFF',
    highlightColor: '#7CFFB2',
    highlightMode: 'scale',
    shadow: { color: 'rgba(0,0,0,0.3)', blur: 6, x: 0, y: 2 },
    container: { type: 'glass', tint: 'light', color: 'rgba(255,255,255,0.14)', radius: 36, padX: 36, padY: 22, blur: 24, border: 'rgba(255,255,255,0.4)' },
    display: 'progressive',
    animation: { type: 'pop', scope: 'word', duration: 0.3 },
    y: 0.7,
    maxWidth: 0.86,
  },
  {
    id: 'glass-slide',
    label: 'Glass 4 tomon',
    category: 'glass',
    font: { family: 'Poppins', weight: 800, size: 64, uppercase: false, letterSpacing: 0 },
    color: '#FFFFFF',
    highlightColor: '#8AB4FF',
    highlightMode: 'color',
    container: { type: 'glass', tint: 'light', color: 'rgba(255,255,255,0.12)', radius: 48, padX: 44, padY: 26, blur: 32, border: 'rgba(255,255,255,0.4)' },
    display: 'progressive',
    animation: { type: 'alternate', scope: 'word', duration: 0.42 },
    y: 0.7,
    maxWidth: 0.86,
  },

  // ---------- Animated (After Effects style) ----------
  {
    id: 'four-sides',
    label: '4 Tomondan',
    category: 'animated',
    font: { family: 'Montserrat', weight: 900, size: 74, uppercase: true, letterSpacing: 0 },
    color: '#FFFFFF',
    highlightColor: '#FFE600',
    highlightMode: 'color',
    stroke: { color: '#000000', width: 6 },
    shadow: softShadow,
    container: noBox,
    display: 'progressive',
    animation: { type: 'alternate', scope: 'word', duration: 0.4 },
    y: 0.7,
    maxWidth: 0.88,
  },
  {
    id: 'rise',
    label: "Ko'tarilish",
    category: 'animated',
    font: { family: 'Outfit', weight: 800, size: 68, uppercase: false, letterSpacing: 0 },
    color: '#FFFFFF',
    highlightColor: '#FF5C8A',
    highlightMode: 'color',
    shadow: softShadow,
    container: noBox,
    display: 'phrase',
    animation: { type: 'slideUp', scope: 'word', duration: 0.4, stagger: 0.07 },
    y: 0.72,
    maxWidth: 0.86,
  },
  {
    id: 'drop',
    label: 'Tushish',
    category: 'animated',
    font: { family: 'Anton', weight: 400, size: 96, uppercase: true, letterSpacing: 1 },
    color: '#FFFFFF',
    highlightColor: '#00E5FF',
    highlightMode: 'color',
    stroke: { color: '#000000', width: 5 },
    container: noBox,
    display: 'progressive',
    animation: { type: 'drop', scope: 'word', duration: 0.6 },
    y: 0.68,
    maxWidth: 0.88,
  },
  {
    id: 'punch',
    label: 'Zarba',
    category: 'animated',
    font: { family: 'BebasNeue', weight: 400, size: 150, uppercase: true, letterSpacing: 2 },
    color: '#FFE600',
    highlightColor: '#FFE600',
    highlightMode: 'none',
    stroke: { color: '#000000', width: 7 },
    shadow: { color: 'rgba(0,0,0,0.6)', blur: 20, x: 0, y: 8 },
    container: noBox,
    display: 'word',
    animation: { type: 'zoomOut', scope: 'word', duration: 0.22 },
    y: 0.6,
    maxWidth: 0.9,
  },
  {
    id: 'spin',
    label: 'Aylanish',
    category: 'animated',
    font: { family: 'Rubik', weight: 800, size: 70, uppercase: true, letterSpacing: 0 },
    color: '#FFFFFF',
    highlightColor: '#FF9F0A',
    highlightMode: 'scale',
    stroke: { color: '#1A1A1A', width: 5 },
    container: noBox,
    display: 'progressive',
    animation: { type: 'rotateIn', scope: 'word', duration: 0.4 },
    y: 0.7,
    maxWidth: 0.88,
  },
  {
    id: 'cinematic',
    label: 'Kino',
    category: 'animated',
    font: { family: 'PlayfairDisplay', weight: 700, italic: true, size: 72, uppercase: false, letterSpacing: 0 },
    color: '#FFFFFF',
    highlightColor: '#FFFFFF',
    highlightMode: 'dim',
    shadow: { color: 'rgba(0,0,0,0.6)', blur: 18, x: 0, y: 4 },
    container: noBox,
    display: 'phrase',
    animation: { type: 'blurIn', scope: 'word', duration: 0.5, stagger: 0.08 },
    y: 0.74,
    maxWidth: 0.84,
  },

  // ---------- Trend ----------
  {
    id: 'hormozi',
    label: 'Hormozi',
    category: 'trend',
    font: { family: 'Montserrat', weight: 900, size: 76, uppercase: true, letterSpacing: 0 },
    color: '#FFFFFF',
    highlightColor: '#3CFF6B',
    highlightMode: 'scale',
    stroke: { color: '#000000', width: 7 },
    shadow: softShadow,
    container: noBox,
    display: 'phrase',
    animation: { type: 'pop', scope: 'phrase', duration: 0.25 },
    y: 0.68,
    maxWidth: 0.88,
  },
  {
    id: 'karaoke-box',
    label: 'Karaoke Box',
    category: 'trend',
    font: { family: 'Poppins', weight: 800, size: 66, uppercase: false, letterSpacing: 0 },
    color: '#FFFFFF',
    highlightColor: '#FFC400',
    highlightTextColor: '#111111',
    highlightMode: 'box',
    shadow: softShadow,
    container: noBox,
    display: 'phrase',
    animation: { type: 'fade', scope: 'phrase', duration: 0.2 },
    y: 0.72,
    maxWidth: 0.86,
  },
  {
    id: 'eclipse',
    label: 'Eclipse',
    category: 'trend',
    font: { family: 'Inter', weight: 600, size: 62, uppercase: false, letterSpacing: 0 },
    color: '#FFFFFF',
    highlightColor: '#B7FF7A',
    highlightMode: 'color',
    container: { type: 'box', color: 'rgba(36,20,64,0.9)', radius: 14, padX: 30, padY: 16 },
    display: 'phrase',
    animation: { type: 'fade', scope: 'phrase', duration: 0.2 },
    y: 0.74,
    maxWidth: 0.84,
  },
  {
    id: 'beast',
    label: 'Beast',
    category: 'trend',
    font: { family: 'Bangers', weight: 400, size: 96, uppercase: true, letterSpacing: 2 },
    color: '#FFFFFF',
    highlightColor: '#FFE600',
    highlightMode: 'scale',
    stroke: { color: '#000000', width: 8 },
    shadow: { color: '#000000', blur: 0, x: 0, y: 8 },
    container: noBox,
    display: 'phrase',
    animation: { type: 'pop', scope: 'word', duration: 0.3, stagger: 0.05 },
    y: 0.68,
    maxWidth: 0.88,
  },
  {
    id: 'neon',
    label: 'Neon',
    category: 'trend',
    font: { family: 'Unbounded', weight: 800, size: 58, uppercase: true, letterSpacing: 1 },
    color: '#E6FBFF',
    highlightColor: '#FF3DF2',
    highlightMode: 'color',
    shadow: { color: '#00E5FF', blur: 24, x: 0, y: 0 },
    container: noBox,
    display: 'phrase',
    animation: { type: 'fade', scope: 'word', duration: 0.3, stagger: 0.06 },
    y: 0.7,
    maxWidth: 0.86,
  },
  {
    id: 'marker',
    label: 'Marker',
    category: 'trend',
    font: { family: 'PermanentMarker', weight: 400, size: 70, uppercase: false, letterSpacing: 0 },
    color: '#FFFFFF',
    highlightColor: '#FF3B6B',
    highlightTextColor: '#FFFFFF',
    highlightMode: 'box',
    shadow: softShadow,
    container: noBox,
    display: 'phrase',
    animation: { type: 'slideRight', scope: 'word', duration: 0.35, stagger: 0.06 },
    y: 0.72,
    maxWidth: 0.86,
  },

  // ---------- Minimal ----------
  {
    id: 'clean',
    label: 'Clean',
    category: 'minimal',
    font: { family: 'Inter', weight: 600, size: 56, uppercase: false, letterSpacing: 0 },
    color: '#FFFFFF',
    highlightColor: '#FFFFFF',
    highlightMode: 'none',
    shadow: { color: 'rgba(0,0,0,0.7)', blur: 10, x: 0, y: 2 },
    container: noBox,
    display: 'phrase',
    animation: { type: 'fade', scope: 'phrase', duration: 0.2 },
    y: 0.8,
    maxWidth: 0.84,
  },
  {
    id: 'classic',
    label: 'Classic',
    category: 'minimal',
    font: { family: 'Montserrat', weight: 800, size: 62, uppercase: true, letterSpacing: 0 },
    color: '#FFFFFF',
    highlightColor: '#FFE600',
    highlightMode: 'color',
    stroke: { color: '#000000', width: 5 },
    container: noBox,
    display: 'phrase',
    animation: { type: 'none', scope: 'phrase', duration: 0.2 },
    y: 0.76,
    maxWidth: 0.86,
  },
];

export const CATEGORIES: { id: CaptionStyle['category']; label: string }[] = [
  { id: 'glass', label: 'Glass' },
  { id: 'animated', label: 'Animatsiya' },
  { id: 'trend', label: 'Trend' },
  { id: 'minimal', label: 'Oddiy' },
];

export const getStyle = (id: string) => STYLES.find((s) => s.id === id) ?? STYLES[0];
